export default {
  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  FORGOT_PASSWORD_PENDING: 'LOGIN_PENDING',
  FORGOT_PASSWORD_SUCCESS: 'LOGIN_SUCCESS',
  FORGOT_PASSWORD_FAILED: 'LOGIN_FAILED',

  VERIFY_RESET_CODE_PENDING: 'FORGOT_PASSWORD_PENDING',
  VERIFY_RESET_CODE_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  VERIFY_RESET_CODE_FAILED: 'FORGOT_PASSWORD_FAILED',

  RESET_PASSWORD_PENDING: 'VERIFY_RESET_CODE_PENDING',
  RESET_PASSWORD_SUCCESS: 'VERIFY_RESET_CODE_SUCCESS',
  RESET_PASSWORD_FAILED: 'VERIFY_RESET_CODE_FAILED',

  REGISTER_PENDING: 'RESET_PASSWORD_PENDING',
  REGISTER_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  REGISTER_FAILED: 'RESET_PASSWORD_FAILED',

  FETCH_CURRENT_USER_PENDING: 'FETCH_CURRENT_USER_PENDING',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILED: 'FETCH_CURRENT_USER_FAILED',

  SAVE_USER_PROFILE_PENDING: 'REGISTER_PENDING',
  SAVE_USER_PROFILE_SUCCESS: 'REGISTER_SUCCESS',
  SAVE_USER_PROFILE_FAILED: 'REGISTER_FAILED',
};
